version: "3.8"

services:
  db:
    image: postgres:17
    container_name: inver-db
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inver-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inver-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  data: